# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

workflows:
  test:
    jobs:
      - node/run:
          app-dir: project
          npm-run: test:ci
